# Generated by Django 5.2.11 on 2026-02-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='variants_json',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='variant_a',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='variant_b',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='variant_c',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='selected_answer',
            field=models.CharField(max_length=1),
        ),
    ]
